sudo: required
services:
   - docker

before_install:
   - docker build -t gaurav/reactapp -f Dockerfile.dev .

script:
   - docker run gaurav/reactapp npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "reactapp"
   env: "Reactapp-env"
   bucket_name: elasticbeanstalk-us-east-2-281006437285
   bucket_path: "reactapp"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"